### ISSUE TITLE
Weiteres Feld "Verfügbar/Nicht verfügbar"

### ISSUE THREAD

**Issue by pheek** [SAProjects/Trainerverfuegbarkeit#3]
Ein weiteres Feld in die DB einpflegen: Bool Verfügbar / nicht verfügbar.
Damit können später die Zeilen Grün bzw Rot markiert werden.
Einfach mit einer Checkbox zu lösen.

Option: color: dann kann auch ein Dropdown mit Farben (grün, rot, gelb, blau) erzeugt werden. Eine kleine Legende zeigt, was es bedeutet:
ROT: Nicht stören
Grün: Verfügbar
Blau: Orange abwesend
Blau: Kurs
... : ...

Dies kann gut im CSS gelöst werden. Beispiel die CSS-klasse ".verfuegbar" könnte einen grünen Hintergrund erzeugen.

**Comment by danfre4santis** [comment]
Wurde mit einem dropdown umgesetzt.
Farben werden via CSS definiert, hat im DOM nichts verloren.
